export const TokenCybersoft =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJCb290Y2FtcCBTw6FuZyAwMiIsIkhldEhhblN0cmluZyI6IjI0LzA4LzIwMjIiLCJIZXRIYW5UaW1lIjoiMTY2MTI5OTIwMDAwMCIsIm5iZiI6MTYzNzM0MTIwMCwiZXhwIjoxNjYxNDQ2ODAwfQ.Jyh-ALPYBzDojZwAY5mCMSzdNFvh1i-5lNzT3RhI0nU";
export const URL = "https://movienew.cybersoft.edu.vn";
