export const SET_BANNER = "SET_BANNER";
export const SET_LIST_PHIM = "SET_LIST_PHIM";
export const GET_THONG_TIN_HE_THONG_RAP = "GET_THONG_TIN_HE_THONG_RAP";
export const SET_PHIM_DANG_CHIEU = "SET_PHIM_DANG_CHIEU";
export const SET_PHIM_SAP_CHIEU = "SET_PHIM_SAP_CHIEU";
export const SET_DETAIL_FILM = "SET_DETAIL_FILM";
